
version: '3'
services:
  node_app:
    container_name: node_app
    restart: always
    build: .
    ports: 
      - "3001:3001"
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    env_file:
      - ./config/doc.env
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'

